apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ojt-was
  namespace: kubeflow
  # finalizers:
  #     - "null"
spec:
  storageClassName: ojt-tibero-was
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/hanjoo/work/OJT/Tibero-ML-pipeline/WAS/static/images