apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tibero-agent-basic-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-09-19T15:29:00.052952',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Hanjoo''s tibero agent
      : basic version", "name": "tibero-agent:basic"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: tibero-agent-basic
  templates:
  - name: sql1
    container:
      env:
      - {name: id, value: hanjoo}
      - {name: pw, value: 1010}
      image: hanjoo8821/jdbc-tibero:basic
    outputs:
      artifacts:
      - {name: sql1-output, path: /tmp/result.txt}
  - name: sql2a
    container:
      env:
      - {name: id, value: hanjoo}
      - {name: pw, value: 1010}
      image: hanjoo8821/jdbc-tibero:basic
    outputs:
      artifacts:
      - {name: sql2a-output, path: /tmp/result.txt}
  - name: sql2b
    container:
      env:
      - {name: id, value: hanjoo}
      - {name: pw, value: 1010}
      image: hanjoo8821/jdbc-tibero:basic
    outputs:
      artifacts:
      - {name: sql2b-output, path: /tmp/result.txt}
  - name: sql3
    container:
      env:
      - {name: id, value: hanjoo}
      - {name: pw, value: 1010}
      image: hanjoo8821/jdbc-tibero:basic
    outputs:
      artifacts:
      - {name: sql3-output, path: /tmp/result.txt}
  - name: tibero-agent-basic
    dag:
      tasks:
      - {name: sql1, template: sql1}
      - name: sql2a
        template: sql2a
        dependencies: [sql1]
      - name: sql2b
        template: sql2b
        dependencies: [sql1]
      - name: sql3
        template: sql3
        dependencies: [sql2a, sql2b]
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
